### PR TITLE
Move seantis specific SCSS files to the according packages

### PR DESCRIPTION
**Pull request by msom**
The according packages are already released:
- seantis.dir.events 1.6
- seantis.dir.base 1.9.1
- seantis.dir.facility 1.8
- seantis.reservation 1.4
- seantis.people 1.1

### CODE REVIEW

**Comment by msom** [comment]
And: Could you please make a release soon (if everything's ok)?

**Comment by msom** [comment]
Anybody?

**Comment by maethu** [comment]
sry for delay...

**Comment by maethu** [comment]
plonetheme.onegov 1.8.0 released!! Thx :sparkles:

**Comment by msom** [comment]
Great! Thanks a lot :)

**Pull request merged**
