### PR TITLE
Unify height and position through margin for foldercontents navbar items

### PR DESCRIPTION
**Pull request by Nachtalb**
Before
---
image

After
---
image

### CODE REVIEW

**Comment by djowett-ftw** [comment]
> #btngroup-mainbuttons {
> 	font-size: 12px;
> }
> #filter input {
> 	padding: 0 0.5em;
> }

Ok you prob need a `height: 28px;` on the input too

**Comment by Nachtalb** [comment]
> fighting it

How so? 

It's quite easy. We make sure that everything has the same height with `height: 30px` (before it was `29.xxx px`) and remove the bottom margin which leads to problems in iZug where the most left part of the navbar was wrapped with `span.https-link` which caused weird margin calculations.

**Comment by djowett-ftw** [comment]
> wrapped with span.https-link which caused weird margin calculations.
I don't see this class in my izug....

I think the bottom-margin affects layout because of the `inline-block` style.  It's the adjustment of the font-size on the body that is hurting this here - as the bottom-margin is in em's, so the font-size needs applying to the containing elements too.

Mobile with your fix looks like it needs a bottom margin :-/

Screenshot 2020-03-09 at 10 51 53

**Comment by Nachtalb** [comment]
@djowett-ftw rebased onto latest master and made sure that it works on both mobile and desktop. The `vertical-align` you see in the SCSS is copied from the `#btngroup-mainbuttons` element. Without that it the navbar groups are offset to each other, so we could either remove it on all or add it to all (doesn't really make a difference).

image

**Comment by Nachtalb** [comment]
Ahh, nice 👍 no need for another PR. I'll add it to this one.

**Pull request merged**
