### PR TITLE
Use the javascript from ftw.mobilenavigation instead of the custom one.

### PR DESCRIPTION
**Pull request by mbaechtold**
This requires an upcoming change/release of ftw.mobilenavigation.
See https://github.com/4teamwork/ftw.mobilenavigation/pull/27.

### CODE REVIEW

**Comment by bierik** [comment]
Merged in #158

**Comment by maethu** [comment]
@bierik There's no merge commit in #158 ?

**Comment by maethu** [comment]
@bierik Please merge #160 into #158 and close this one.

**Comment by bierik** [comment]
Merge #160 into #158

**Pull request closed without merging**
