### PR TITLE
remove useless sl stuff from print

### PR DESCRIPTION
**Pull request by Tschanzt**
@maethu I hid some stuff which doesn't benefit anyone in print.

### CODE REVIEW

**Comment by mbaechtold** [comment]
@Tschanzt, could you please add some screenshots (before, after) highlighting the removed elements?

**Comment by mbaechtold** [comment]
@Tschanzt, could you please rebase onto `master` and provide some screenshots?

**Comment by mbaechtold** [comment]
Oh and please add an entry to the changelog 😉

**Comment by Tschanzt** [comment]
before:
screen shot 2016-09-14 at 10 06 03
after:
screen shot 2016-09-14 at 10 07 40

**Comment by Tschanzt** [comment]
@mbaechtold updated.

**Comment by mbaechtold** [comment]
Cool, thank you very much @Tschanzt 👍

**Pull request merged**
